[build]
  functions = "my-backend/functions"  # Directory for serverless functions
  publish = "app/dist"                # Directory to publish the frontend

[dev]
  functions = "my-backend/functions"
